package com.rules.chapter32

import com.rules.model.Person
import com.rules.model.Car

rule "chater32-test1"
no-loop true
when
    $p : Person(age < 19)
    if($p.getAge() == 20) do[modifyAge]
then
    System.out.println("chater32-test1 executed");
then[modifyAge]
    modify($p){
        setAge(17)
    }
end


rule "chater32-test2"
    extends "chater32-test1"
when
    $c : Car(discount < 80)
then
    System.out.println("chater32-test2 executed");
end
